### PR TITLE
[.gitignore] Added default one from `cargo new --lib`

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by rhymu8354** [comment]
I'm not sure I like all the rustfmt changes...

**Comment by SamuelMarks** [comment]
@rhymu8354 `rustfmt` is the standard formatter for Rust. Unless you have a good reason—like your using a different formatter—the Rust community recommends sticking to it.

The popular crates use it. Go has their gofmt and this is basically equivalent (only opt-in).

**Comment by rhymu8354** [comment]
I'd like a rustfmt.toml configured more to my liking.  I'll look into it.

**Comment by SamuelMarks** [comment]
@rhymu8354 Okay this PR is just the .gitignore now

**Comment by rhymu8354** [comment]
I learned a lot today, setting up rustfmt.  Unfortunately a lot of settings I want are unstable and require the nightly build.

**Pull request merged**
